project:
  type: website

website:
  title: "R Syntax"
  repo-actions: [edit, source, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house-fill
format:
  html:
    theme: cosmo
    title-block-banner: true



